# revision 23440
# category Package
# catalog-ctan /macros/latex/contrib/tsemlines/tsemlines.sty
# catalog-date 2011-06-28 13:55:08 +0200
# catalog-license pd
# catalog-version 1.0
Name:		texlive-tsemlines
Version:	1.0
Release:	1
Summary:	Support for the ancient \emline macro
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/macros/latex/contrib/tsemlines/tsemlines.sty
License:	PD
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/tsemlines.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(post):	texlive-tlpkg
Conflicts:	texlive-texmf <= 20110705-3

%description
Occasional Documents appear, that use graphics generated by
texcad from the emtex distribution. These documents often use
the \emline macro, which produced lines at an arbitrary
orientation. The present package emulates the macro, using
TikZ.

%pre
    %_texmf_mktexlsr_pre

%post
    %_texmf_mktexlsr_post

%preun
    if [ $1 -eq 0 ]; then
	%_texmf_mktexlsr_pre
    fi

%postun
    if [ $1 -eq 0 ]; then
	%_texmf_mktexlsr_post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/tex/latex/tsemlines/tsemlines.sty
%doc %{_tlpkgobjdir}/*.tlpobj

#-----------------------------------------------------------------------
%prep
%setup -c -a0

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar tex %{buildroot}%{_texmfdistdir}
mkdir -p %{buildroot}%{_tlpkgobjdir}
cp -fpa tlpkg/tlpobj/*.tlpobj %{buildroot}%{_tlpkgobjdir}
