Name:		texlive-tsemlines
Version:	23440
Release:	1
Summary:	Support for the ancient \emline macro
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/macros/latex/contrib/tsemlines/tsemlines.sty
License:	PD
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/tsemlines.r%{version}.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
Occasional Documents appear, that use graphics generated by
texcad from the emtex distribution. These documents often use
the \emline macro, which produced lines at an arbitrary
orientation. The present package emulates the macro, using
TikZ.

%post
%{_sbindir}/texlive.post

%postun
if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/tex/latex/tsemlines/tsemlines.sty

#-----------------------------------------------------------------------
%prep
%autosetup -p1 -c

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar tex %{buildroot}%{_texmfdistdir}
